name: Run Scenarios

on:
  workflow_dispatch:
    inputs:
      agent_id:
        description: 'Agent ID'
        required: true
      scenarios:
        description: 'Comma-separated list of scenario IDs'
        required: true
      frequency:
        description: 'Number of times to run each scenario'
        required: false
        default: '1'
      timeout:
        description: 'Timeout in seconds'
        required: false
        default: '3600'

jobs:
  run-scenarios:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run scenarios
      env:
        API_BASE_URL: ${{ secrets.API_BASE_URL }}
        API_KEY: ${{ secrets.API_KEY }}
        AGENT_ID: ${{ github.event.inputs.agent_id }}
        SCENARIOS: ${{ github.event.inputs.scenarios }}
        FREQUENCY: ${{ github.event.inputs.frequency }}
        TIMEOUT: ${{ github.event.inputs.timeout }}
      run: python run_scenarios.py 